### ISSUE TITLE
Replace jQuery with a lightweight HTTP Request library

### ISSUE THREAD

**Issue by adnanbrq** [andvote/andvote#5]
In andvote you make use of jQuery's .get and .ajax methods.
This is a bit of an overkill so it should be replaced with a lighter library like for example [superagent](https://www.npmjs.com/package/superagent)?

**Comment by bookercodes** [comment]
Definitely!

**Comment by bookercodes** [comment]
Would love a pull request for this btw!

**Comment by adnanbrq** [comment]
@alexbooker maybe it isn't even necessary to switch to a new library while we just can replace jQuery with simple XHR. What do you think? 🤔

**Comment by bookercodes** [comment]
Hm. I would rather we use a lib. I like:
-  [axios](https://github.com/mzabriskie/axios)
- [fetch-polyfill](https://github.com/github/fetch)
- [atomic](https://github.com/toddmotto/atomic)

I don't mind what we use really.

**Comment by adnanbrq** [comment]
I'm going to vote for [axios](https://github.com/mzabriskie/axios) because it does work on browsers and node unlike [fetch-polyfill](https://github.com/github/fetch) which requires [node-fetch](https://github.com/bitinn/node-fetch).

**Comment by bookercodes** [comment]
:heart: axios
