### ISSUE TITLE
Implement server side rendering?

### ISSUE THREAD

**Issue by adnanbrq** [andvote/andvote#8]
#### Benefits
- Users with disabled JavaScript can access the site, vote, view or even create polls.
#### Negative side-effects
- The user has to refresh the page in order to see updates made to the poll.
- The user will only be able to enter an fixed amount of options as there is no way to add them dynamically.
- More / much more requests as the user has to refresh the page as described earlier.

It might be good for people who haven't used server side rendering yet.
What you think @alexbooker and @DmsChrisPena ?

**Comment by bookercodes** [comment]
If I understand correctly, you're suggesting that we basically remove the [`client`](https://github.com/andvote/andvote/tree/master/client) code and instead rely on server-side templating? I would never do that but I _would_ consider using server-side rendering as part of a [universal React application](https://medium.com/@firasd/quick-start-tutorial-universal-react-with-server-side-rendering-76fe5363d6e/) - that would allow users without JS to use the poll without introducing the negative side-effects you listed.

As with anything, I think introducing universal JS adds complexity to the code base and that complexity base needs to be justified. At the moment, I'm not sure if that complexity is justified but I'd love to hear your thoughts.

Thanks for the suggestion, @adnanbrq :smile:
